//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4214
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DbModel", "FK_Roles_ControlsRoles_Control", "Controls", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Right), "Roles_Controls", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Role_Right))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DbModel", "FK_RolesControls_Role", "Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Role), "Roles_Controls", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Role_Right))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DbModel", "FK_UserRoles_Role", "Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Role), "User_Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.User_Role))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DbModel", "FK_UserRoles_User", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.User), "User_Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.User_Role))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("DbModel", "FK_Reports_User", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.User), "Reports", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Report))]

// Original file name:
// Generation date: 29.6.2011 г. 10:40 ч.
namespace DataAccess
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for RightSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Right> RightSet
        {
            get
            {
                if ((this._RightSet == null))
                {
                    this._RightSet = base.CreateQuery<Right>("[RightSet]");
                }
                return this._RightSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Right> _RightSet;
        /// <summary>
        /// There are no comments for RoleSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Role> RoleSet
        {
            get
            {
                if ((this._RoleSet == null))
                {
                    this._RoleSet = base.CreateQuery<Role>("[RoleSet]");
                }
                return this._RoleSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Role> _RoleSet;
        /// <summary>
        /// There are no comments for Role_RightSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Role_Right> Role_RightSet
        {
            get
            {
                if ((this._Role_RightSet == null))
                {
                    this._Role_RightSet = base.CreateQuery<Role_Right>("[Role_RightSet]");
                }
                return this._Role_RightSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Role_Right> _Role_RightSet;
        /// <summary>
        /// There are no comments for User_RoleSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User_Role> User_RoleSet
        {
            get
            {
                if ((this._User_RoleSet == null))
                {
                    this._User_RoleSet = base.CreateQuery<User_Role>("[User_RoleSet]");
                }
                return this._User_RoleSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User_Role> _User_RoleSet;
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> UserSet
        {
            get
            {
                if ((this._UserSet == null))
                {
                    this._UserSet = base.CreateQuery<User>("[UserSet]");
                }
                return this._UserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _UserSet;
        /// <summary>
        /// There are no comments for ReportSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Report> ReportSet
        {
            get
            {
                if ((this._ReportSet == null))
                {
                    this._ReportSet = base.CreateQuery<Report>("[ReportSet]");
                }
                return this._ReportSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Report> _ReportSet;
        /// <summary>
        /// There are no comments for RightSet in the schema.
        /// </summary>
        public void AddToRightSet(Right right)
        {
            base.AddObject("RightSet", right);
        }
        /// <summary>
        /// There are no comments for RoleSet in the schema.
        /// </summary>
        public void AddToRoleSet(Role role)
        {
            base.AddObject("RoleSet", role);
        }
        /// <summary>
        /// There are no comments for Role_RightSet in the schema.
        /// </summary>
        public void AddToRole_RightSet(Role_Right role_Right)
        {
            base.AddObject("Role_RightSet", role_Right);
        }
        /// <summary>
        /// There are no comments for User_RoleSet in the schema.
        /// </summary>
        public void AddToUser_RoleSet(User_Role user_Role)
        {
            base.AddObject("User_RoleSet", user_Role);
        }
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
        /// <summary>
        /// There are no comments for ReportSet in the schema.
        /// </summary>
        public void AddToReportSet(Report report)
        {
            base.AddObject("ReportSet", report);
        }
    }
    /// <summary>
    /// There are no comments for DbModel.Right in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Right")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Right : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Right object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of name.</param>
        public static Right CreateRight(long id, string name)
        {
            Right right = new Right();
            right.ID = id;
            right.name = name;
            return right;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Roles_Rights in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Roles_ControlsRoles_Control", "Roles_Controls")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Role_Right> Roles_Rights
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Role_Right>("DbModel.FK_Roles_ControlsRoles_Control", "Roles_Controls");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Role_Right>("DbModel.FK_Roles_ControlsRoles_Control", "Roles_Controls", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DbModel.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Role")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Role : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of name.</param>
        public static Role CreateRole(long id, string name)
        {
            Role role = new Role();
            role.ID = id;
            role.name = name;
            return role;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Role_Rights in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_RolesControls_Role", "Roles_Controls")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Role_Right> Role_Rights
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Role_Right>("DbModel.FK_RolesControls_Role", "Roles_Controls");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Role_Right>("DbModel.FK_RolesControls_Role", "Roles_Controls", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User_Roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_UserRoles_Role", "User_Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User_Role> User_Roles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User_Role>("DbModel.FK_UserRoles_Role", "User_Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User_Role>("DbModel.FK_UserRoles_Role", "User_Roles", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DbModel.Role_Right in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Role_Right")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Role_Right : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Role_Right object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="enabled">Initial value of enabled.</param>
        /// <param name="visible">Initial value of visible.</param>
        public static Role_Right CreateRole_Right(long id, bool enabled, bool visible)
        {
            Role_Right role_Right = new Role_Right();
            role_Right.ID = id;
            role_Right.enabled = enabled;
            role_Right.visible = visible;
            return role_Right;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property enabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool enabled
        {
            get
            {
                return this._enabled;
            }
            set
            {
                this.OnenabledChanging(value);
                this.ReportPropertyChanging("enabled");
                this._enabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("enabled");
                this.OnenabledChanged();
            }
        }
        private bool _enabled;
        partial void OnenabledChanging(bool value);
        partial void OnenabledChanged();
        /// <summary>
        /// There are no comments for Property visible in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool visible
        {
            get
            {
                return this._visible;
            }
            set
            {
                this.OnvisibleChanging(value);
                this.ReportPropertyChanging("visible");
                this._visible = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("visible");
                this.OnvisibleChanged();
            }
        }
        private bool _visible;
        partial void OnvisibleChanging(bool value);
        partial void OnvisibleChanged();
        /// <summary>
        /// There are no comments for Right in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Roles_ControlsRoles_Control", "Controls")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Right Right
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Right>("DbModel.FK_Roles_ControlsRoles_Control", "Controls").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Right>("DbModel.FK_Roles_ControlsRoles_Control", "Controls").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Right in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Right> RightReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Right>("DbModel.FK_Roles_ControlsRoles_Control", "Controls");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Right>("DbModel.FK_Roles_ControlsRoles_Control", "Controls", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_RolesControls_Role", "Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Role Role
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("DbModel.FK_RolesControls_Role", "Roles").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("DbModel.FK_RolesControls_Role", "Roles").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Role> RoleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("DbModel.FK_RolesControls_Role", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Role>("DbModel.FK_RolesControls_Role", "Roles", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DbModel.User_Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DbModel", Name="User_Role")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User_Role : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User_Role object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="active">Initial value of active.</param>
        public static User_Role CreateUser_Role(long id, bool active)
        {
            User_Role user_Role = new User_Role();
            user_Role.ID = id;
            user_Role.active = active;
            return user_Role;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        private bool _active;
        partial void OnactiveChanging(bool value);
        partial void OnactiveChanged();
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_UserRoles_Role", "Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Role Role
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("DbModel.FK_UserRoles_Role", "Roles").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("DbModel.FK_UserRoles_Role", "Roles").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Role> RoleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("DbModel.FK_UserRoles_Role", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Role>("DbModel.FK_UserRoles_Role", "Roles", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_UserRoles_User", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("DbModel.FK_UserRoles_User", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("DbModel.FK_UserRoles_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("DbModel.FK_UserRoles_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("DbModel.FK_UserRoles_User", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DbModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DbModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="username">Initial value of username.</param>
        /// <param name="password">Initial value of password.</param>
        /// <param name="name">Initial value of name.</param>
        /// <param name="isAdmin">Initial value of isAdmin.</param>
        /// <param name="mainAdmin">Initial value of mainAdmin.</param>
        /// <param name="isActive">Initial value of isActive.</param>
        public static User CreateUser(long id, string username, string password, string name, bool isAdmin, bool mainAdmin, bool isActive)
        {
            User user = new User();
            user.ID = id;
            user.username = username;
            user.password = password;
            user.name = name;
            user.isAdmin = isAdmin;
            user.mainAdmin = mainAdmin;
            user.isActive = isActive;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this._username;
            }
            set
            {
                this.OnusernameChanging(value);
                this.ReportPropertyChanging("username");
                this._username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("username");
                this.OnusernameChanged();
            }
        }
        private string _username;
        partial void OnusernameChanging(string value);
        partial void OnusernameChanged();
        /// <summary>
        /// There are no comments for Property password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this.ReportPropertyChanging("password");
                this._password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("password");
                this.OnpasswordChanged();
            }
        }
        private string _password;
        partial void OnpasswordChanging(string value);
        partial void OnpasswordChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property isAdmin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAdmin
        {
            get
            {
                return this._isAdmin;
            }
            set
            {
                this.OnisAdminChanging(value);
                this.ReportPropertyChanging("isAdmin");
                this._isAdmin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("isAdmin");
                this.OnisAdminChanged();
            }
        }
        private bool _isAdmin;
        partial void OnisAdminChanging(bool value);
        partial void OnisAdminChanged();
        /// <summary>
        /// There are no comments for Property mainAdmin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool mainAdmin
        {
            get
            {
                return this._mainAdmin;
            }
            set
            {
                this.OnmainAdminChanging(value);
                this.ReportPropertyChanging("mainAdmin");
                this._mainAdmin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mainAdmin");
                this.OnmainAdminChanged();
            }
        }
        private bool _mainAdmin;
        partial void OnmainAdminChanging(bool value);
        partial void OnmainAdminChanged();
        /// <summary>
        /// There are no comments for Property isActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool isActive
        {
            get
            {
                return this._isActive;
            }
            set
            {
                this.OnisActiveChanging(value);
                this.ReportPropertyChanging("isActive");
                this._isActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("isActive");
                this.OnisActiveChanged();
            }
        }
        private bool _isActive;
        partial void OnisActiveChanging(bool value);
        partial void OnisActiveChanged();
        /// <summary>
        /// There are no comments for User_Roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_UserRoles_User", "User_Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User_Role> User_Roles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User_Role>("DbModel.FK_UserRoles_User", "User_Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User_Role>("DbModel.FK_UserRoles_User", "User_Roles", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Reports in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Reports_User", "Reports")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Report> Reports
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Report>("DbModel.FK_Reports_User", "Reports");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Report>("DbModel.FK_Reports_User", "Reports", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for DbModel.Report in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Report")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Report : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Report object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="description">Initial value of description.</param>
        /// <param name="dateAdded">Initial value of dateAdded.</param>
        /// <param name="visible">Initial value of visible.</param>
        /// <param name="solved">Initial value of solved.</param>
        /// <param name="about">Initial value of about.</param>
        public static Report CreateReport(long id, string description, global::System.DateTime dateAdded, bool visible, bool solved, string about)
        {
            Report report = new Report();
            report.ID = id;
            report.description = description;
            report.dateAdded = dateAdded;
            report.visible = visible;
            report.solved = solved;
            report.about = about;
            return report;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property dateAdded in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime dateAdded
        {
            get
            {
                return this._dateAdded;
            }
            set
            {
                this.OndateAddedChanging(value);
                this.ReportPropertyChanging("dateAdded");
                this._dateAdded = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateAdded");
                this.OndateAddedChanged();
            }
        }
        private global::System.DateTime _dateAdded;
        partial void OndateAddedChanging(global::System.DateTime value);
        partial void OndateAddedChanged();
        /// <summary>
        /// There are no comments for Property visible in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool visible
        {
            get
            {
                return this._visible;
            }
            set
            {
                this.OnvisibleChanging(value);
                this.ReportPropertyChanging("visible");
                this._visible = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("visible");
                this.OnvisibleChanged();
            }
        }
        private bool _visible;
        partial void OnvisibleChanging(bool value);
        partial void OnvisibleChanged();
        /// <summary>
        /// There are no comments for Property solved in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool solved
        {
            get
            {
                return this._solved;
            }
            set
            {
                this.OnsolvedChanging(value);
                this.ReportPropertyChanging("solved");
                this._solved = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("solved");
                this.OnsolvedChanged();
            }
        }
        private bool _solved;
        partial void OnsolvedChanging(bool value);
        partial void OnsolvedChanged();
        /// <summary>
        /// There are no comments for Property about in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string about
        {
            get
            {
                return this._about;
            }
            set
            {
                this.OnaboutChanging(value);
                this.ReportPropertyChanging("about");
                this._about = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("about");
                this.OnaboutChanged();
            }
        }
        private string _about;
        partial void OnaboutChanging(string value);
        partial void OnaboutChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Reports_User", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("DbModel.FK_Reports_User", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("DbModel.FK_Reports_User", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("DbModel.FK_Reports_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("DbModel.FK_Reports_User", "User", value);
                }
            }
        }
    }
}
